CREATE TABLE POKEMON (
    ID_POKEMON NUMBER PRIMARY KEY,
    NUMERO_POKEMON NUMBER NOT NULL,
    NOME_POKEMON VARCHAR2(255) NOT NULL,
    LEVEL_POKEMON NUMBER NOT NULL,
    PESO_POKEMON DECIMAL(3,2) NOT NULL,
    ALTURA_POKEMON DECIMAL(3,2) NOT NULL,
    CATEGORIA_POKEMON VARCHAR2(255) NOT NULL,
    REGIAO_DOMINANTE_POKE_LENDARIO VARCHAR2(255),
    HP_STATUS NUMBER NOT NULL,
    ATAQUE_STATUS NUMBER NOT NULL,
    DEFESA_STATUS NUMBER,
    ATAQUE_ESPECIAL_STATUS NUMBER NOT NULL,
    DEFESA_ESPECIAL_STATUS NUMBER NOT NULL,
    VELOCIDADE_STATUS NUMBER NOT NULL
);

CREATE TABLE TIPO (
    ID_TIPO NUMBER PRIMARY KEY,
    NOME_TIPO VARCHAR2(255),
    FORTE_CONTRA_TIPO VARCHAR2(255) NOT NULL,
    FRACO_CONTRA_TIPO VARCHAR2(255) NOT NULL,
    RESISTENTE_A_TIPO VARCHAR2(255) NOT NULL,
    VULNERAVEL_A_TIPO VARCHAR2(255) NOT NULL
);

CREATE TABLE HABILIDADE (
    ID_HABILIDADE NUMBER PRIMARY KEY,
    NOME_HABILIDADE VARCHAR2(255) NOT NULL,
    MULT_DE_PODER_HABILIDADE DECIMAL(3,2) NOT NULL
);

CREATE TABLE EVOLUCAO (
    ID_EVOLUCAO NUMBER PRIMARY KEY,
    ID_POKE_ESTAGIO_1_EVOLUCAO NUMBER,
    ID_POKE_ESTAGIO_2_EVOLUCAO NUMBER,
    ID_POKE_ESTAGIO_3_EVOLUCAO NUMBER
);   

CREATE TABLE POKEMON_TIPO (
    FK_TIPO_ID_TIPO NUMBER,
    FK_POKEMON_ID_POKEMON NUMBER
);

CREATE TABLE POKEMON_HABILIDADE (
    FK_HABILIDADE_ID_HABILIDADE NUMBER,
    FK_POKEMON_ID_POKEMON NUMBER
);

CREATE TABLE POKEMON_EVOLUCAO (
    FK_POKEMON_ID_POKEMON NUMBER,
    FK_EVOLUCAO_ID_EVOLUCAO NUMBER
);

ALTER TABLE EVOLUCAO ADD CONSTRAINT FK_POKEMON_ESTAGE_1
    FOREIGN KEY (ID_POKE_ESTAGIO_1_EVOLUCAO)
    REFERENCES POKEMON (ID_POKEMON); 
   
ALTER TABLE EVOLUCAO ADD CONSTRAINT FK_POKEMON_ESTAGE_2
    FOREIGN KEY (ID_POKE_ESTAGIO_2_EVOLUCAO)
    REFERENCES POKEMON (ID_POKEMON);
   
ALTER TABLE EVOLUCAO ADD CONSTRAINT FK_POKEMON_ESTAGE_3
    FOREIGN KEY (ID_POKE_ESTAGIO_3_EVOLUCAO)
    REFERENCES POKEMON (ID_POKEMON);
 
ALTER TABLE POKEMON_TIPO ADD CONSTRAINT FK_POKEMON_TIPO_1
    FOREIGN KEY (FK_TIPO_ID_TIPO)
    REFERENCES TIPO (ID_TIPO);   
 
ALTER TABLE POKEMON_TIPO ADD CONSTRAINT FK_POKEMON_TIPO_2
    FOREIGN KEY (FK_POKEMON_ID_POKEMON)
    REFERENCES POKEMON (ID_POKEMON); 
   
 
ALTER TABLE POKEMON_HABILIDADE ADD CONSTRAINT FK_POKEMON_HABILIDADE_1
    FOREIGN KEY (FK_HABILIDADE_ID_HABILIDADE)
    REFERENCES HABILIDADE (ID_HABILIDADE);
    
 
ALTER TABLE POKEMON_HABILIDADE ADD CONSTRAINT FK_POKEMON_HABILIDADE_2
    FOREIGN KEY (FK_POKEMON_ID_POKEMON)
    REFERENCES POKEMON (ID_POKEMON);
    
 
ALTER TABLE POKEMON_EVOLUCAO ADD CONSTRAINT FK_POKEMON_EVOLUCAO_1
    FOREIGN KEY (FK_POKEMON_ID_POKEMON)
    REFERENCES POKEMON (ID_POKEMON)
    ON DELETE SET NULL;
 
ALTER TABLE POKEMON_EVOLUCAO ADD CONSTRAINT FK_POKEMON_EVOLUCAO_2
    FOREIGN KEY (FK_EVOLUCAO_ID_EVOLUCAO)
    REFERENCES EVOLUCAO (ID_EVOLUCAO)
    ON DELETE SET NULL;  
   
CREATE SEQUENCE seq_ID_POKEMON
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE seq_ID_HABILIDADE
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE seq_ID_TIPO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE seq_ID_EVOLUCAO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
   