CREATE TABLE POKEMON (
    ID_POKEMON NUMBER PRIMARY KEY,
    NUMERO_POKEMON NUMBER,
    NOME_POKEMON VARCHAR2(255),
    LEVEL_POKEMON NUMBER,
    PESO_POKEMON DECIMAL(3,2),
    ALTURA_POKEMON DECIMAL(3,2),
    CATEGORIA_POKEMON VARCHAR2(255),
    REGIAO_DOMINANTE_POKE_LENDARIO VARCHAR2(255),
    HP_STATUS NUMBER,
    ATAQUE_STATUS NUMBER,
    DEFESA_STATUS NUMBER,
    ATAQUE_ESPECIAL_STATUS NUMBER,
    DEFESA_ESPECIAL_STATUS NUMBER,
    VELOCIDADE_STATUS NUMBER,
    FK_ID_EVOLUCAO NUMBER
);


ALTER TABLE POKEMON ADD CONSTRAINT FK_ID_EVOLUCAO
    FOREIGN KEY (FK_ID_EVOLUCAO)
    REFERENCES EVOLUCAO (ID_EVOLUCAO);

CREATE TABLE HABILIDADE (
    ID_HABILIDADE NUMBER PRIMARY KEY,
    NOME_HABILIDADE VARCHAR2(255),
    MULT_DE_PODER_HABILIDADE DECIMAL(3,2)
);

CREATE TABLE EVOLUCAO (
    ID_EVOLUCAO NUMBER PRIMARY KEY,
    ID_POKE_ESTAGIO_1_EVOLUCAO NUMBER,
    ID_POKE_ESTAGIO_2_EVOLUCAO NUMBER,
    ID_POKE_ESTAGIO_3_EVOLUCAO NUMBER
);

ALTER TABLE EVOLUCAO ADD CONSTRAINT FK_POKE_STAGE_1
    FOREIGN KEY (ID_POKE_ESTAGIO_1_EVOLUCAO)
    REFERENCES POKEMON (ID_POKEMON);
   
ALTER TABLE EVOLUCAO ADD CONSTRAINT FK_POKE_STAGE_2
    FOREIGN KEY (ID_POKE_ESTAGIO_2_EVOLUCAO)
    REFERENCES POKEMON (ID_POKEMON);
   
ALTER TABLE EVOLUCAO ADD CONSTRAINT FK_POKE_STAGE_3
    FOREIGN KEY (ID_POKE_ESTAGIO_3_EVOLUCAO)
    REFERENCES POKEMON (ID_POKEMON);

CREATE TABLE POKEMON_TIPO (
    NOME_TIPO VARCHAR2(255),
    FK_POKEMON_ID_POKEMON NUMBER,
    ID_POKEMON_TIPO NUMBER PRIMARY KEY
);

ALTER TABLE POKEMON_TIPO ADD CONSTRAINT FK_ID_POKEMON_TIPO_DEF
    FOREIGN KEY (FK_POKEMON_ID_POKEMON)
    REFERENCES POKEMON (ID_POKEMON);

CREATE TABLE POKEMON_HABILIDADE (
    FK_HABILIDADE_ID_HABILIDADE NUMBER,
    FK_POKEMON_ID_POKEMON NUMBER
);

 
ALTER TABLE POKEMON_HABILIDADE ADD CONSTRAINT FK_POKEMON_HABILIDADE_1
    FOREIGN KEY (FK_HABILIDADE_ID_HABILIDADE)
    REFERENCES HABILIDADE (ID_HABILIDADE);
 
ALTER TABLE POKEMON_HABILIDADE ADD CONSTRAINT FK_POKEMON_HABILIDADE_2
    FOREIGN KEY (FK_POKEMON_ID_POKEMON)
    REFERENCES POKEMON (ID_POKEMON);
   
CREATE SEQUENCE seq_ID_POKEMON
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE seq_ID_HABILIDADE
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE seq_ID_POKEMON_TIPO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE seq_ID_EVOLUCAO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;