INSERT INTO POKEMON P 
(P.ID_POKEMON, P.NUMERO_POKEMON, P.NOME_POKEMON, P.LEVEL_POKEMON, 
P.PESO_POKEMON, P.ALTURA_POKEMON, P.CATEGORIA_POKEMON, 
P.REGIAO_DOMINANTE_POKE_LENDARIO, P.HP_STATUS, P.ATAQUE_STATUS, 
P.DEFESA_STATUS, P.ATAQUE_ESPECIAL_STATUS, P.DEFESA_ESPECIAL_STATUS, P.VELOCIDADE_STATUS)
VALUES 
(SEQ_ID_POKEMON.nextval, 1, 'Bulssauro', 1, 6.9, 0.7, 'Semente', NULL, 45, 49, 49, 65, 65, 45);

INSERT INTO POKEMON P 
(P.ID_POKEMON, P.NUMERO_POKEMON, P.NOME_POKEMON, P.LEVEL_POKEMON, 
P.PESO_POKEMON, P.ALTURA_POKEMON, P.CATEGORIA_POKEMON, 
P.REGIAO_DOMINANTE_POKE_LENDARIO, P.HP_STATUS, P.ATAQUE_STATUS, 
P.DEFESA_STATUS, P.ATAQUE_ESPECIAL_STATUS, P.DEFESA_ESPECIAL_STATUS, P.VELOCIDADE_STATUS)
VALUES 
(SEQ_ID_POKEMON.nextval, 2, 'Ivyssauro', 16, 13.0, 1.0, 'Semente', NULL, 60, 62, 63, 80, 80, 60);

INSERT INTO POKEMON P 
(P.ID_POKEMON, P.NUMERO_POKEMON, P.NOME_POKEMON, P.LEVEL_POKEMON, 
P.PESO_POKEMON, P.ALTURA_POKEMON, P.CATEGORIA_POKEMON, 
P.REGIAO_DOMINANTE_POKE_LENDARIO, P.HP_STATUS, P.ATAQUE_STATUS, 
P.DEFESA_STATUS, P.ATAQUE_ESPECIAL_STATUS, P.DEFESA_ESPECIAL_STATUS, P.VELOCIDADE_STATUS)
VALUES 
(SEQ_ID_POKEMON.nextval, 3, 'Venussauro', 32, 100.0, 2.0, 'Semente', NULL, 80, 82, 83, 100, 100, 80);


INSERT INTO HABILIDADE H 
(H.ID_HABILIDADE, H.NOME_HABILIDADE, H.MULT_DE_PODER_HABILIDADE)
VALUES
(SEQ_ID_HABILIDADE.nextval, 'Intimidar', 1.2);

INSERT INTO HABILIDADE H 
(H.ID_HABILIDADE, H.NOME_HABILIDADE, H.MULT_DE_PODER_HABILIDADE)
VALUES
(SEQ_ID_HABILIDADE.nextval, 'Super crescimento', 1.2);

INSERT INTO HABILIDADE H 
(H.ID_HABILIDADE, H.NOME_HABILIDADE, H.MULT_DE_PODER_HABILIDADE)
VALUES
(SEQ_ID_HABILIDADE.nextval, 'Chama', 1.2);


INSERT INTO POKEMON_HABILIDADE PH 
(PH.FK_POKEMON_ID_POKEMON, PH.FK_HABILIDADE_ID_HABILIDADE)
VALUES
(1, 2);

INSERT INTO POKEMON_HABILIDADE PH 
(PH.FK_POKEMON_ID_POKEMON, PH.FK_HABILIDADE_ID_HABILIDADE)
VALUES
(3, 1);

INSERT INTO POKEMON_HABILIDADE PH 
(PH.FK_POKEMON_ID_POKEMON, PH.FK_HABILIDADE_ID_HABILIDADE)
VALUES
(4, 1);

INSERT INTO POKEMON_HABILIDADE PH 
(PH.FK_POKEMON_ID_POKEMON, PH.FK_HABILIDADE_ID_HABILIDADE)
VALUES
(4, 2);


SELECT * FROM POKEMON;

SELECT * FROM HABILIDADE;

SELECT * FROM POKEMON_TIPO;

SELECT * FROM POKEMON_HABILIDADE;

SELECT P.NOME_POKEMON, H.NOME_HABILIDADE 
FROM POKEMON P
INNER JOIN POKEMON_HABILIDADE PH ON (P.ID_POKEMON = PH.FK_POKEMON_ID_POKEMON)
INNER JOIN HABILIDADE H ON (PH.FK_HABILIDADE_ID_HABILIDADE = H.ID_HABILIDADE);


INSERT INTO POKEMON_TIPO PT 
(PT.ID_POKEMON_TIPO, PT.NOME_TIPO, PT.FK_POKEMON_ID_POKEMON)
VALUES
(SEQ_ID_POKEMON_TIPO.nextval, 'PLANTA', 1);

INSERT INTO POKEMON_TIPO PT 
(PT.ID_POKEMON_TIPO, PT.NOME_TIPO, PT.FK_POKEMON_ID_POKEMON)
VALUES
(SEQ_ID_POKEMON_TIPO.nextval, 'PLANTA', 3);

INSERT INTO POKEMON_TIPO PT 
(PT.ID_POKEMON_TIPO, PT.NOME_TIPO, PT.FK_POKEMON_ID_POKEMON)
VALUES
(SEQ_ID_POKEMON_TIPO.nextval, 'PLANTA', 4);

INSERT INTO POKEMON_TIPO PT 
(PT.ID_POKEMON_TIPO, PT.NOME_TIPO, PT.FK_POKEMON_ID_POKEMON)
VALUES
(SEQ_ID_POKEMON_TIPO.nextval, 'VENENOSO', 4);

SELECT P.NOME_POKEMON, PT.NOME_TIPO
FROM POKEMON P
INNER JOIN POKEMON_TIPO PT ON (PT.FK_POKEMON_ID_POKEMON = P.ID_POKEMON);



INSERT INTO EVOLUCAO E
(E.ID_EVOLUCAO, E.ID_POKE_ESTAGIO_1_EVOLUCAO, E.ID_POKE_ESTAGIO_2_EVOLUCAO, E.ID_POKE_ESTAGIO_3_EVOLUCAO)
VALUES
(SEQ_ID_EVOLUCAO.nextval, 1, 3, 4);

SELECT * FROM EVOLUCAO;

UPDATE POKEMON P
	SET P.FK_ID_EVOLUCAO = 1
	WHERE P.ID_POKEMON = 3;
UPDATE POKEMON P
	SET P.FK_ID_EVOLUCAO = 1
	WHERE P.ID_POKEMON = 4;


SELECT P.NOME_POKEMON
FROM POKEMON P
INNER JOIN EVOLUCAO E ON (E.ID_EVOLUCAO = P.FK_ID_EVOLUCAO);

SELECT * FROM POKEMON

