INSERT INTO POKEMON P 
(P.ID_POKEMON, P.NUMERO_POKEMON, P.NOME_POKEMON, P.LEVEL_POKEMON, 
P.PESO_POKEMON, P.ALTURA_POKEMON, P.CATEGORIA_POKEMON, 
P.REGIAO_DOMINANTE_POKE_LENDARIO, P.HP_STATUS, P.ATAQUE_STATUS, 
P.DEFESA_STATUS, P.ATAQUE_ESPECIAL_STATUS, P.DEFESA_ESPECIAL_STATUS, P.VELOCIDADE_STATUS)
VALUES 
(SEQ_ID_POKEMON.nextval, 1, 'Bulssauro', 1, 6.9, 0.7, 'Semente', NULL, 45, 49, 49, 65, 65, 45);

INSERT INTO POKEMON P 
(P.ID_POKEMON, P.NUMERO_POKEMON, P.NOME_POKEMON, P.LEVEL_POKEMON, 
P.PESO_POKEMON, P.ALTURA_POKEMON, P.CATEGORIA_POKEMON, 
P.REGIAO_DOMINANTE_POKE_LENDARIO, P.HP_STATUS, P.ATAQUE_STATUS, 
P.DEFESA_STATUS, P.ATAQUE_ESPECIAL_STATUS, P.DEFESA_ESPECIAL_STATUS, P.VELOCIDADE_STATUS)
VALUES 
(SEQ_ID_POKEMON.nextval, 2, 'Ivyssauro', 16, 13.0, 1.0, 'Semente', NULL, 60, 62, 63, 80, 80, 60);

INSERT INTO POKEMON P 
(P.ID_POKEMON, P.NUMERO_POKEMON, P.NOME_POKEMON, P.LEVEL_POKEMON, 
P.PESO_POKEMON, P.ALTURA_POKEMON, P.CATEGORIA_POKEMON, 
P.REGIAO_DOMINANTE_POKE_LENDARIO, P.HP_STATUS, P.ATAQUE_STATUS, 
P.DEFESA_STATUS, P.ATAQUE_ESPECIAL_STATUS, P.DEFESA_ESPECIAL_STATUS, P.VELOCIDADE_STATUS)
VALUES 
(SEQ_ID_POKEMON.nextval, 3, 'Venussauro', 32, 100.0, 2.0, 'Semente', NULL, 80, 82, 83, 100, 100, 80);


INSERT INTO HABILIDADE H 
(H.ID_HABILIDADE, H.NOME_HABILIDADE, H.MULT_DE_PODER_HABILIDADE)
VALUES
(SEQ_ID_HABILIDADE.nextval, 'Intimidar', 1.2);

INSERT INTO HABILIDADE H 
(H.ID_HABILIDADE, H.NOME_HABILIDADE, H.MULT_DE_PODER_HABILIDADE)
VALUES
(SEQ_ID_HABILIDADE.nextval, 'Super crescimento', 1.2);

INSERT INTO HABILIDADE H 
(H.ID_HABILIDADE, H.NOME_HABILIDADE, H.MULT_DE_PODER_HABILIDADE)
VALUES
(SEQ_ID_HABILIDADE.nextval, 'Chama', 1.2);


INSERT INTO POKEMON_HABILIDADE PH 
(PH.FK_POKEMON_ID_POKEMON, PH.FK_HABILIDADE_ID_HABILIDADE)
VALUES
(1, 9);

INSERT INTO POKEMON_HABILIDADE PH 
(PH.FK_POKEMON_ID_POKEMON, PH.FK_HABILIDADE_ID_HABILIDADE)
VALUES
(2, 8);

INSERT INTO POKEMON_HABILIDADE PH 
(PH.FK_POKEMON_ID_POKEMON, PH.FK_HABILIDADE_ID_HABILIDADE)
VALUES
(3, 10);


SELECT * FROM POKEMON;

SELECT * FROM HABILIDADE;

SELECT * FROM POKEMON_TIPO;

SELECT * FROM TIPO;

SELECT * FROM POKEMON_HABILIDADE;

SELECT P.NOME_POKEMON, H.NOME_HABILIDADE 
FROM POKEMON P
INNER JOIN POKEMON_HABILIDADE PH ON (P.ID_POKEMON = PH.FK_POKEMON_ID_POKEMON)
INNER JOIN HABILIDADE H ON (PH.FK_HABILIDADE_ID_HABILIDADE = H.ID_HABILIDADE);


INSERT INTO TIPO T 
(T.ID_TIPO, T.NOME_TIPO)
VALUES
(SEQ_ID_TIPO.nextval, 'PLANTA');

INSERT INTO TIPO T 
(T.ID_TIPO, T.NOME_TIPO)
VALUES
(SEQ_ID_TIPO.nextval, 'VENENOSO');


INSERT INTO POKEMON_TIPO PT 
(PT.FK_TIPO_ID_TIPO, PT.FK_POKEMON_ID_POKEMON)
VALUES
(1, 1);

INSERT INTO POKEMON_TIPO PT 
(PT.FK_TIPO_ID_TIPO, PT.FK_POKEMON_ID_POKEMON)
VALUES
(2, 1);

INSERT INTO POKEMON_TIPO PT 
(PT.FK_TIPO_ID_TIPO, PT.FK_POKEMON_ID_POKEMON)
VALUES
(1, 2);

INSERT INTO POKEMON_TIPO PT 
(PT.FK_TIPO_ID_TIPO, PT.FK_POKEMON_ID_POKEMON)
VALUES
(2, 2);

INSERT INTO POKEMON_TIPO PT 
(PT.FK_TIPO_ID_TIPO, PT.FK_POKEMON_ID_POKEMON)
VALUES
(1, 3);

INSERT INTO POKEMON_TIPO PT 
(PT.FK_TIPO_ID_TIPO, PT.FK_POKEMON_ID_POKEMON)
VALUES
(2, 3);


SELECT P.NOME_POKEMON, T.NOME_TIPO
FROM POKEMON P
INNER JOIN POKEMON_TIPO PT ON (P.ID_POKEMON = PT.FK_POKEMON_ID_POKEMON)
INNER JOIN TIPO T ON (T.ID_TIPO = PT.FK_TIPO_ID_TIPO);

INSERT INTO EVOLUCAO E
(E.ID_EVOLUCAO, E.ID_POKE_ESTAGIO_1_EVOLUCAO, E.ID_POKE_ESTAGIO_2_EVOLUCAO, E.ID_POKE_ESTAGIO_3_EVOLUCAO)
VALUES
(SEQ_ID_EVOLUCAO.nextval, 1, 5, 8);

SELECT * FROM EVOLUCAO;

SELECT * FROM POKEMON_EVOLUCAO;

INSERT INTO POKEMON_EVOLUCAO PE 
(PE.FK_POKEMON_ID_POKEMON, PE.FK_EVOLUCAO_ID_EVOLUCAO)
VALUES 
(1, 1)

INSERT INTO POKEMON_EVOLUCAO PE 
(PE.FK_POKEMON_ID_POKEMON, PE.FK_EVOLUCAO_ID_EVOLUCAO)
VALUES 
(2, 1)

INSERT INTO POKEMON_EVOLUCAO PE 
(PE.FK_POKEMON_ID_POKEMON, PE.FK_EVOLUCAO_ID_EVOLUCAO)
VALUES 
(3, 1)

SELECT P.NOME_POKEMON, E.ID_POKE_ESTAGIO_1_EVOLUCAO, E.ID_POKE_ESTAGIO_2_EVOLUCAO, E.ID_POKE_ESTAGIO_3_EVOLUCAO 
FROM POKEMON P
INNER JOIN POKEMON_EVOLUCAO PE ON (PE.FK_POKEMON_ID_POKEMON = P.ID_POKEMON)
INNER JOIN EVOLUCAO E ON (PE.FK_EVOLUCAO_ID_EVOLUCAO = E.ID_EVOLUCAO);


